# 干垃圾配置
digital_device: # 开关量
  addr: 1 # 站号
  input: # 读输入离散量 02
    td01: 1 # 门口有人
    td02: 2 # 门口有人
    td03: 3 # 
    td04: 4 
    td05: 5
    td06: 6
    td07: 7
    td08: 8 # 门打开的限位开关
    td09: 9 # 关门限位
    td010: 10
    td011: 11 # 
    td012: 12 # 

  output: # 读/写输出线圈 01/05
    d01:
      - 1 # h1
      - 2 # h2
      - 6 # l1
      - 5 # l2
    d02:
      - 3
      - 4
      - 8
      - 7
    d03:
      - 9
      - 10
      - 14
      - 13
    d04: 15 # 用 d04 : \n - 13形式需要修改初始化方法，电子锁管理员流程, output_switch device
    d10: 16 # 垃圾箱内灯

analog_device: # 模拟量
  addr: 1 # 实际调试前需要修改站号
  input:
    force: 1 # 读入寄存器 04