# 湿垃圾配置
digital_device: # 开关量
  addr: 2 # 站号
  input: # 读输入离散量 02
    td01: 1 
    td02: 2 
    td03: 3
    td04: 4 
    td05: 5
    td06: 6
    td07: 7

  output: # 读/写输出线圈 01/05
    d01:
      - 1 # h1
      - 2 # h2
      - 6 # l1
      - 5 # l2
    d02:
      - 3
      - 4
      - 8
      - 7
    d04: 10 # 
    d08: 14 #
    d09: 15 #

analog_device: # 模拟量
  addr: 2
  input:
    force: 1 # 指流程图中的d03